services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestock_app
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:yourappkey=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=sifedb
      - DB_USERNAME=root
      - DB_PASSWORD=
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0
    container_name: gestock_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sifedb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
